### PR TITLE
Use new login URL

### PR DESCRIPTION
**Pull request by githubert**
Use the new login URL.

### CODE REVIEW

**Comment by modulo11** [comment]
You would need to add `login.retest.de` to the `permissions` in `manifest.json` as well.

**Comment by githubert** [comment]
Is `*.retest.org` in that case obsolete?

**Comment by modulo11** [comment]
No, as it's needed for accessing parts of the services.

**Comment by githubert** [comment]
Okay, this needs some more work on the background services, as well some more changes to the extension.

**Comment by githubert** [comment]
Tested it, and everything works as expected. GMs can be created and the user is directed to the dashboard if 'compare' is selected.

**Comment by modulo11** [comment]
These are changes are already on the master and released by Jerry.

**Pull request closed without merging**
