### PR TITLE
Add mergify config from retest/recheck

### PR DESCRIPTION
**Pull request by diba1013**
This is copied from retest/recheck/.mergify.yaml

This PR needs to be merged manually, after that, simply comment with `@Mergifyio refresh` on existing PRs. From that point on, mergify should do that on its own.

### CODE REVIEW

**Review by githubert — APPROVED** [review]
:+1: — thanks a lot!

**Comment by diba1013** [comment]
Oh, and you might want to adapt the branch protection rules to allow mergify respect branch up to date and so that it can merge on its own.

**Comment by githubert** [comment]
I think I'm missing permissions on this repository in order to change any settings — so @roesslerj probably has to change this :)

**Comment by diba1013** [comment]
@beatngu13 could you update the branch protection settings accordingly?

**Comment by beatngu13** [comment]
Updated the protections for both `develop` and `master`. Please note since there is no build or code analysis, the only check that currently applies is the CLA verification. Also since the repo uses Git Flow and not GitHub Flow, there may be some special cases we haven't considered so far in our Mergify setup.

**Comment by githubert** [comment]
Thanks a lot! Let's see if this works out. I thinking about adding at least some checks, maybe it is also a good idea to see what other projects for Chrome extensions do.

**Pull request merged**
