### PR TITLE
Use upn for "Logged in as …" message

### PR DESCRIPTION
**Pull request by githubert**
The pop-up window showing what is going on would show "Logged in as undefined.", after using the field `upn` everything works again as expected.

### CODE REVIEW

**Comment by roesslerj** [comment]
Better have Joe look at this...

**Review by modulo11 — APPROVED** [review]

**Comment by githubert** [comment]
@Mergifyio refresh

**Comment by githubert** [comment]
@Mergifyio refresh

**Comment by githubert** [comment]
@cla-bot check

**Pull request merged**
